version: '3.8'

services:
  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  ai-python-service:
    build:
      context: F:/AiApi
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - F:/AiApi:/app
    networks:
      - app-network

  myapi:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ai-python-service
      - sqlserverdb
    ports:
      - "8090:8080"
      - "8091:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserverdb;Database=MyApiDb;User Id=sa;Password=Your_password123;TrustServerCertificate=true

volumes:
  sqlserverdata:

networks:
  app-network:
    driver: bridge  